version: '3.8'

services:
  client:
    image: tassianna/restaurant-app:client
    container_name: client
    ports:
      - 5173:5173

  backend:
    image: tassianna/restaurant-app:backend
    container_name: backend
    ports:
      - 6001:6001

