version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 5173:5173
    networks:
      - test

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 6001:6001
    networks:
      - test

networks:
  test:
    driver: bridge