---
- name: Setup Maintenance Instance
  hosts: maintenance
  become: yes  # Use sudo
  tasks:
    - name: Ensure Ansible is installed
      apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Clone the Git repository
      git:
        repo: https://github.com/Tassianna/restaurant-app.git  # Replace with your repo URL
        dest: /home/ubuntu/restaurant-app # Specify the path where you want to clone the repo
        clone: yes
        force: yes  # Ensures the repo is cloned even if it already exists
        update: true

    - name: Copy london.key to maintenance instance
      copy:
        src: "{{ local_key }}" # this is passed via playbook command in automated script
        dest: /home/ubuntu/london_key.pem

    # Use ansible builtin file to change permissions and owner of key
    - name: Change Owner and permissions of key
      ansible.builtin.file:
        path: /home/ubuntu/london_key.pem
        owner: ubuntu 
        group: ubuntu
        mode: '0600'

    # Use retrieved values from terraform output to create new hosts file in cloned repository
    - name: Creating a host file with content
      copy:
        dest: "/home/ubuntu/restaurant-app/ansible/hosts"
        content: |
          [frontend]
          frontend ansible_host={{ frontend }} port=3000 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/london_key.pem

          [backend]
          items ansible_host={{ items }} port=3003 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/london_key.pem
          auth ansible_host={{ auth }} port=3001 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/london_key.pem
          discounts ansible_host={{ discounts }} port=3002 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/london_key.pem

          [haproxy]
          haproxy ansible_host={{ haproxy }} ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/london_key.pem

